rmp135/sql-ts

- README.md
provide additional information to using `mssql` dialect with `msnodesqlv8` driver (Windows only)
> add information about `msnodesqlv8`

- README.md
- dist/TableTasks.js
- dist/Typings.d.ts
- src/TableTasks.spec.ts
- src/TableTasks.ts
- src/Typings.ts
We are interested in using this library to extract typescript definitions from our database, however, we wanted the ability to generate concrete classes instead of typescript interfaces for use tooling that will automatically read and write these database objects to the db. 
These changes should not change the default behavior of the generator in anyway, but they do give more flexibility to users.
> Allow for additional customization of table definitions

- dist/DatabaseTasks.d.ts
- dist/DatabaseTasks.js
- dist/index.js
- src/DatabaseTasks.spec.ts
- src/DatabaseTasks.ts
- src/index.spec.ts
- src/index.ts
This separates the decoration of the database object from the stringifyDatabase command so that we can operate on the full object after calling toObject, but before applying the template.
> Create full database object prior to applying template

- README.md
- dist/TableTasks.js
- src/TableTasks.spec.ts
- src/TableTasks.ts
The current `interfaceNameFormat` config property allows transforming the table name into the interface name. However currently some transformations are not possible, in particular those that change the case of the word.
This pull request adds the special transformation "PascalCase", which allows transforming table names all lowercase separated by underscore to PascalCase. For example, `user_sessions` will be transformed to `UserSessions`.
> Add support for special interfaceNameFormat value "PascalCase"

- README.md
- dist/TableTasks.js
- dist/Typings.d.ts
- dist/cli.js
- src/TableTasks.ts
- src/Typings.ts
- src/cli.ts
Currently the config allows you to specify what tables should be included in generated types. However in some cases you might want to include *all* the tables, *except* a few system ones. This new property `excludedTables` allows doing this by specifying a list of tables that should be excluded.
(Note: I also made a small change - I've removed the "." after the generate file path so that it can be more easily copied and pasted or clicked on from the terminal)
> Added support for config property "excludedTables"

- src/DatabaseTasks.ts
Hi there,
The order of the tables is not declared in pg `Adapter`.  This causes the server to return tables in different orders over time and different computers, which creates false-diffs in source control management and merge pain when collaborating.
This PR sorts `database.tables` alphabetically by name right before they are grouped together. 
This should prevent the false-diffs in SCM.
> Sort type definitions returned by `DatabaseTasks.stringifyDatabase`

- .gitignore
- dist/TypeMap.d.ts
- dist/TypeMap.js
- dist/template.handlebars
- package-lock.json
- src/ColumnTasks.ts
- src/TypeMap.ts
- src/template.handlebars
I have updated the handlebar template to put column names in the double quote to prevent compatibility problems with ts/js property formating. 
it can handle column names that are valid in SQL server but not valid in js/ts like: 
- `SubCO/POCONum`
- `P-UN`
- `Receiver#`
- `L-%Comp`
Also added missing types in sql server to TypeMap file:
- tinyint
- uniqueidentifier
> bug fix in generating column with special names in SQL Server

- package.json
This PR specifies peerDependencies of dependencies that are intended for the user to satisfy. This is required for pnp module resolution to function (yarn pnp, yarn berry - like in the PR for dependency knex https://github.com/knex/knex/pull/3081). Without this this module doesn't work with yarn pnp (as the db driver cannot be required).
nb; nice module, it took me a few tries to find it but its great :smile:
> Fix: Adds peerDependencies

- README.md
I'm not sure if there's any way to know what the schema name is for SQLite with the current implementation. What I always do is add "console" statement in sql-ts to find out, but it would be better to document it. I believe it's always "main" for SQLite.
> Mention the schema name for SQLite databases

- src/TypeMap.ts
Resolves TS2304 `Cannot find name 'buffer'. ts(2304)`
Update to reference the `Buffer` class as defined within `@types/node/globals.d.ts`
> Fix Buffer type name

- dist/TypeMap.d.ts
- dist/TypeMap.js
- package.json
Knex already uses ^5.0.0 while sql-ts has ^4.1.1 this can lead to dependency hickups.
I ran _yarn run build_ and _yarn run test_ successfully.
> match sqllite version with knex projects version

- src/Adapters/mysql.ts
MySQL 8 also brings back attributes in all upper-case...so aliasing fixes both problems...
`IS_NULLABLE` is what is currently being returned, when we when `isNullable` is what is being read.
> isNullable currently broken. The attribute name is mismatched.

- src/TypeMap.ts
Ran into the problem that postgres columns created as `real` resulted in `any` types in the TS output. Debugging a bit, I noted that sql-ts was receiving `float4` as the column type.
> Add `float4` and `float8` data types

- src/Adapters/mssql.ts
fix SQL server case sensitive engine error `Invalid object name 'information_schema.table_constraints'.`
> fix SQL server case sensitive engine errors

- src/TypeMap.ts
I ran into some `any` types, so I realized these Postgres types are missing in the type map. Solved it by overriding them in the config, but it might be nice to add them to the default map. There was a duplicate `timestamp`, so I used that one for `timestamptz`.
> Add int2, citext and timestamptz data types to map

- src/SharedTasks.ts
- src/specs/SharedTasks.spec.ts
Regarding issue #82 I've removed `replace` method that removes number from column property name.
Also I've removed the test code that tested the removing number part of the code.
> Fix #82 - Remove line that parses number into string

- src/Adapters/postgres.ts
attidentity: If a zero byte (''), then not an identity column. Otherwise, a = generated always, d = generated by default.
https://www.postgresql.org/docs/10/catalog-pg-attribute.html
===
```sql
CREATE TABLE test
(
sequence      INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pkey PRIMARY KEY,
generated     INTEGER GENERATED ALWAYS AS sequence + 1 STORED,
);
```
```ts
// before
interface test {
sequence: number
generated: number
}
// after 
interface test {
sequence?: number
generated?: number
}
```
> feat(postgres): support generated columns and identities

- src/TypeMap.ts
Occasionally, Postgres does arbitrarily some type conversion.
For example, `char` to `bpchar` → “Blank padded char”.
Query: `SELECT * FROM pg_type WHERE typname ilike '%char%'`
This commit aims to avoid `any` when possible by default.
> Add better mappings for PostgreSQL types.

- src/Adapters/sqlite.ts
- src/specs/Adapters/sqlite.spec.ts
Hi there!
I've been trying to use this library as [schemats](https://github.com/sweetiq/schemats) doesn't support SQLite. Nice job!
I found a couple of issues with the SQLite adapter, though.
The first one is the fact that `PRAGMA table_info(<table>)` column `pk` type is `INTEGER`, not a "boolean" (`0 | 1`), with the number representing [the index of the column in the primary key for columns that are part of the primary key](https://www.sqlite.org/pragma.html#pragma_table_info). I've corrected the types and the code to correctly detect primary keys with index greater than 0.
Second, a column being part of a primary key doesn't mean that it's value is optional. A column with [`AUTOINCREMENT`](https://www.sqlite.org/autoinc.html) is, but checking for that [requires data to have been …
> Improve SQLite adapter correctness.

- src/ColumnTasks.ts
This PR will sort the columns based on lexicographic order instead of whatever the underlying adapter returns
Currently, the order of the columns in the generated types is undefined.  In Postgres (which is what we use), the DB appears to return columns are returned in the order they are created in the database.  This is fine and usually results in no issues if columns are created across multiple transactions which is the normal use-case for us.  (We use Knex migrations and commit them to the codebase as we need to migrate the DB).  
However, if you create all columns in a single transaction, this ordering is violated.  This is what we encountered when we tried to generate types from a test DB which we bring up from scratch in CI to run DB-driven tests against. 
With this PR, the order …
> Sort columns based on lexicographic order

- src/Adapters/postgres.ts
Your fix to #88 is almost right, but the call to `Array.sort()` is missing the correct comparison function.
> Pass comparison function when sorting enums

- src/TableTasks.ts
- src/specs/TableTasks.spec.ts
Just a little tweak :) I have a table called "dependencies" that was being changed to "dependencie" when singularTableNames was set! I've added a test for the new behaviour so if you're happy including my change, it should be an easy merge.
Thanks!
Alex
> enabled singularTableNames to fix 'ies' plurals

- src/TypeMap.ts
UUID arrays did not have an entry in the built-in type map so they were being compiled to `any`.  
This PR adds support for them to the built-in type map so they are correctly typed as `string[]`
> Add support for arrays of UUIDs

- src/ColumnTasks.ts
- src/ConfigTasks.ts
- src/Typings.ts
In Config, provide a new option called `sortColumn`,
sortColumn can have 2 values,
- origin
- alphabet(default)
If set sortColumn to origin, we won't sort columns and generate interface with original order.
Related issue: https://github.com/rmp135/sql-ts/issues/127
> Add "sortColumn" option for handling columns order

- src/Adapters/postgres.ts
In the currently released version postgres table partitions are treated as separate tables. This can result in an explosion of duplicate types.
This PR ignores partitions when listing tables. The other db adapters may also benefit from similar changes.
> Don't treat postgres table partitions as separate tables
